val nameParameter : MethodDeclaration.cJMethodParameter
val ageParameter : MethodDeclaration.cJMethodParameter
val setNameParameterList : MethodDeclaration.cJMethodParameterList
val emptyParameterList : MethodDeclaration.cJMethodParameterList
val assignStmt : ExpDeclaration.superExp
val declareStmt : ExpDeclaration.superExp
val varList : ExpDeclaration.varList
val newStmt : ExpDeclaration.superExp
val assignStmt2 : ExpDeclaration.superExp
val compoundStmt : ExpDeclaration.superExp
val compoundStmt2 : ExpDeclaration.superExp
val ifStmt : ExpDeclaration.superExp
val returnStmt : ExpDeclaration.superExp
val setNameMethod : MethodDeclaration.cJMethod
val getNameMethod : MethodDeclaration.cJMethod
val methodList : MethodDeclaration.cJMethodList
val nameField : FieldDeclaration.cJField
val ageField : FieldDeclaration.cJField
val fieldList : FieldDeclaration.cJFieldList
val personClass : ClassDeclaration.cJClass
val personClass2 : ClassDeclaration.cJClass
val personClass3 : ClassDeclaration.cJClass
val program : ProgramDeclaration.cJProgram
val v3 : string
val rez : bool
val pairs : string
val allPairs : string
