val nameParameter : MethodDeclaration.cJMethodParameter
val ageParameter : MethodDeclaration.cJMethodParameter
val setNameParameterList : MethodDeclaration.cJMethodParameterList
val emptyParameterList : MethodDeclaration.cJMethodParameterList
val declareStmt : ExpDeclaration.superExp
val newStmt : ExpDeclaration.exp3
val assignStmt : ExpDeclaration.superExp
val assignStmt2 : ExpDeclaration.superExp
val compoundStmt : ExpDeclaration.superExp
val compoundStmt2 : ExpDeclaration.superExp
val ifStmt : ExpDeclaration.superExp
val constExp1 : ExpDeclaration.exp
val declareStmt2 : ExpDeclaration.superExp
val varList : ExpDeclaration.varList
val methodCallStmt : ExpDeclaration.superExp
val constExp2 : ExpDeclaration.superExp
val compountStmt3 : ExpDeclaration.superExp
val setNameMethod : MethodDeclaration.cJMethod
val mainMethod : MethodDeclaration.cJMethod
val methodList : MethodDeclaration.cJMethodList
val nameField : FieldDeclaration.cJField
val ageField : FieldDeclaration.cJField
val fieldList : FieldDeclaration.cJFieldList
val personClass : ClassDeclaration.cJClass
val personClass2 : ClassDeclaration.cJClass
val personClass3 : ClassDeclaration.cJClass
val program : ProgramDeclaration.cJProgram
val stringProgram : string
