val nameParameter : MethodDeclaration.cJMethodParameter
val ageParameter : MethodDeclaration.cJMethodParameter
val setNameParameterList : MethodDeclaration.cJMethodParameterList
val emptyParameterList : MethodDeclaration.cJMethodParameterList
val assignStmt : StmtDeclaration.stmt
val ifStmt : StmtDeclaration.stmt
val returnStmt : StmtDeclaration.stmt
val setNameMethod : MethodDeclaration.cJMethod
val getNameMethod : MethodDeclaration.cJMethod
val methodList : MethodDeclaration.cJMethodList
val nameField : FieldDeclaration.cJField
val ageField : FieldDeclaration.cJField
val fieldList : FieldDeclaration.cJFieldList
val personClass : ClassDeclaration.cJClass
val program : ProgramDeclaration.cJProgram
val v3 : string
